## 常见操作说明

In [3]:
import numpy as np

In [4]:
# ?np.random.choice
# choice(a, size=None, replace=True, p=None)
# 如果 a 是array，则从array中采用
# 如果 a 是 int ，则 np.arange(a) 中采样
np.random.choice(5, 3)

array([3, 3, 2])

In [6]:
# p 代表每个元素的概率，不传则是均匀分布
np.random.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0])

array([2, 3, 2])

In [8]:
# size 表示了输出的性状
np.random.choice(5, (2,1,2)).shape

(2, 1, 2)

In [13]:
# replace 表示是否重复采样
np.random.choice(5,5,replace=True)

array([1, 3, 2, 2, 3])

In [12]:
np.random.choice(5,5,replace=False)

array([4, 2, 3, 1, 0])

In [2]:
# ?np.where
# where(condition, [x, y]), 如果只有condition，返回满足的下标 (array(行),array(列))
# np.where(mask)[0] 返回满足的行